### PR TITLE
It70g2019 feature

### PR DESCRIPTION
**Pull request by andreailic**

### CODE REVIEW

**Comment by dangershony** [comment]
Is this a mistake PR?

**Comment by andreailic** [comment]
I subsequently worked on our project with Code Smells, these are my changes and hopefully the last pull request..

**Comment by sondreb** [comment]
> I subsequently worked on our project with Code Smells, these are my changes and hopefully the last pull request..

I don't understand what you are doing or what is going on, there is a bunch of strange GitHub accounts contributing on this, only sensible one is @draganovik. We are not going to accept this pull request for very obvious reasons.

If you want to contribute to Blockcore, please let us know and provide small and sensible pull requests that can be reviewed and vetted properly.

**Comment by andreailic** [comment]
My bad, it was a mistake!

**Comment by sondreb** [comment]
> My bad, it was a mistake!

Can you please explain what you are doing?

**Pull request closed without merging**
