### PR TITLE
UI Fixes & Updates

### PR DESCRIPTION
**Pull request by thecrypt0hunter**
- Fix error & improve coins sent message

### CODE REVIEW

**Comment by turcol** [comment]
@thecrypt0hunter it looks great. Just a comment: after you send the coins, should we reset all the values, or at least the password?

You can double click on the "Send Coins" and the transaction will go thru ... quiet easy to send multiple transactions

image

**Comment by dangershony** [comment]
> You can double click on the "Send Coins" and the transaction will go thru ... quiet easy to send multiple transactions

hmm are you suggesting its good to send many trx?

**Comment by sondreb** [comment]
No, he is not suggesting that, it's the opposite. He is warning that people might send duplicate transactions by mistake, since the password is still there.

**Comment by thecrypt0hunter** [comment]
I agree it should reset the input values after it sent. Should I reset just the password or all values?

**Comment by thecrypt0hunter** [comment]
This is fixed here - https://github.com/block-core/blockcore/pull/188

**Pull request merged**
