### PR TITLE
It6g2019 feature

### PR DESCRIPTION
**Pull request by markorakic777**

### CODE REVIEW

**Comment by sondreb** [comment]
Hi, can you please explain what is the purpose of this PR and what the goal is? There are some obvious breaking changes here so can't be accepted, but don't want to do full review unless purpose is stated?

**Comment by sondreb** [comment]
@markorakic777 @andrejkatin @draganovik

Please reply =)

**Comment by draganovik** [comment]
> @markorakic777 @andrejkatin @draganovik
> 
> Please reply =)

@sondreb Sorry about this, this pull request was supposed to be submitted to our internal fork, we are analyzing this repository with SonarCloud platform and these changes are not meant to be merged back to the block-core/blockcore repository.

We'll make sure we don’t do this again in the future,
Thanks for understanding!

**Comment by sondreb** [comment]
> > @markorakic777 @andrejkatin @draganovik
> > Please reply =)
> 
> @sondreb Sorry about this, this pull request was supposed to be submitted to our internal fork, we are analyzing this repository with SonarCloud platform and these changes are not meant to be merged back to the block-core/blockcore repository.
> 
> We'll make sure we don’t do this again in the future, Thanks for understanding!

Ok thanks for the reply, good luck with your adventures!

**Pull request closed without merging**
