### PR TITLE
Add Rutanio DNS daemon

### PR DESCRIPTION
**Pull request by turcol**

### CODE REVIEW

**Comment by sondreb** [comment]
I don't think we need to have specific DNS nodes in the repo, the generic node project should rather be updated with support for launching in either regular or DNS mode?

**Comment by dangershony** [comment]
> I don't think we need to have specific DNS nodes in the repo, the generic node project should rather be updated with support for launching in either regular or DNS mode?

you mean the `Blockcore.Node` project?

**Comment by sondreb** [comment]
Yes, just have a flag or parameter and make additional options in the launchsettings file.

**Comment by turcol** [comment]
@dangershony could you please close this PR .. We will be doing the changes for the DNS as suggested by @sondreb ; then this PR  won't be needed

**Pull request closed without merging**
