### PR TITLE
Add XDS network

### PR DESCRIPTION
**Pull request by dangershony**
This is still WIP

Based on https://github.com/sonofsatoshi2020/xds

### CODE REVIEW

**Comment by thecrypt0hunter** [comment]
Some feedback:

1. The data directory has moved from .fullnoderoot/xds/MainNet to .Blockcore/xds/XdsMain. This means people will likely end up needing to re-sync
2. I couldn't copy my wallet across to Blockcore, I guess I'll have to recover from seed words.

**Comment by sondreb** [comment]
I believe that wallet copy should be responsibility of the UI, not the FN.

**Comment by thecrypt0hunter** [comment]
What I mean is that the Blockcore XDS daemon won't load when I manually copied my old XDS wallet file over to the Blockcore data directory. So I am going to try to restore from seed words using the new daemon.

**Comment by dangershony** [comment]
@thecrypt0hunter yes resync is needed anyway because of a bug fix.

Its odd wallet doesn't work, I cant try it myself as well.

**Comment by thecrypt0hunter** [comment]
This codebase also has the "dust" error.

**Comment by dangershony** [comment]
All tests passed on this

**Comment by thecrypt0hunter** [comment]
Using this API in swagger:
```
/api/Staking/getStakingNotExpired
```

I receive this error:
```
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
```

It works fine if I call using CURL command

**Pull request merged**
