### PR TITLE
Coldstake redeem bug

### PR DESCRIPTION
**Pull request by dangershony**
This PR fixes a cold stake bug found recently where hot/cold keys are use in more then one redeem script

https://github.com/block-core/blockcore/issues/395

### CODE REVIEW

**Comment by dangershony** [comment]
Still need to fix the tests

**Comment by dangershony** [comment]
This is now ready to review, I will run tests locally.
@sondreb please review (also @DavidGershony you can try to have a look)

**Comment by dangershony** [comment]
closes #395

**Comment by dangershony** [comment]
All tests passed locally

**Comment by dangershony** [comment]
@sondreb reminder to review

**Review by sondreb — APPROVED** [review]
Looks good, have not run and verified, but read all the changes.

**Comment by dangershony** [comment]
I believe @miladsoft has tested it as well is that correct?

**Comment by miladsoft** [comment]
Yes, I have tested it and I am using it And it works properly

**Pull request merged**
